<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab Ten – Point Estimation – Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a2a938b4dd5711f7a799c87bd16ba44c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Lab10/Lab10WriteUp.html">Lab Ten – Point Estimation</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Portfolio</a> 
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab2/Lab2WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab Two – Basic Tasks in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab3/Lab3WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab Three – Matrices and Data Frames in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab4/Lab4WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab Four – Programming in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab5-6/Lab5WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab Five-Six – Data Wrangling in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab8/Lab8WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab Eight – Probability</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab10/Lab10WriteUp.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lab Ten – Point Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Lab11/Lab11WriteUp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab Eleven – Point Estimation and Resampling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Unit2Review/review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit 2 Review – tidyverse and ggplot</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lab-8-notes" id="toc-lab-8-notes" class="nav-link active" data-scroll-target="#lab-8-notes"><span class="header-section-number">1</span> Lab 8 Notes</a>
  <ul class="collapse">
  <li><a href="#althams-multiplicative-binomial-distribution" id="toc-althams-multiplicative-binomial-distribution" class="nav-link" data-scroll-target="#althams-multiplicative-binomial-distribution"><span class="header-section-number">1.1</span> Altham’s Multiplicative Binomial Distribution</a></li>
  </ul></li>
  <li><a href="#althams-multiplicative-beta-binomial-distribution" id="toc-althams-multiplicative-beta-binomial-distribution" class="nav-link" data-scroll-target="#althams-multiplicative-beta-binomial-distribution"><span class="header-section-number">2</span> Altham’s Multiplicative Beta Binomial Distribution</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">3</span> Question 1</a>
  <ul class="collapse">
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a"><span class="header-section-number">3.1</span> Part a</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b"><span class="header-section-number">3.2</span> Part b</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c"><span class="header-section-number">3.3</span> Part c</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">4</span> Question 2</a>
  <ul class="collapse">
  <li><a href="#part-a-1" id="toc-part-a-1" class="nav-link" data-scroll-target="#part-a-1"><span class="header-section-number">4.1</span> Part a</a></li>
  <li><a href="#part-b-1" id="toc-part-b-1" class="nav-link" data-scroll-target="#part-b-1"><span class="header-section-number">4.2</span> Part b</a></li>
  <li><a href="#part-c-1" id="toc-part-c-1" class="nav-link" data-scroll-target="#part-c-1"><span class="header-section-number">4.3</span> Part c</a></li>
  <li><a href="#part-d" id="toc-part-d" class="nav-link" data-scroll-target="#part-d"><span class="header-section-number">4.4</span> Part d</a></li>
  </ul></li>
  <li><a href="#lab-10" id="toc-lab-10" class="nav-link" data-scroll-target="#lab-10"><span class="header-section-number">5</span> Lab 10</a>
  <ul class="collapse">
  <li><a href="#summarize-the-2024-data" id="toc-summarize-the-2024-data" class="nav-link" data-scroll-target="#summarize-the-2024-data"><span class="header-section-number">5.1</span> Summarize the 2024 Data</a></li>
  <li><a href="#althams-multiplicative-binomial-distribution-1" id="toc-althams-multiplicative-binomial-distribution-1" class="nav-link" data-scroll-target="#althams-multiplicative-binomial-distribution-1"><span class="header-section-number">5.2</span> Altham’s Multiplicative Binomial Distribution</a></li>
  <li><a href="#althams-multiplicative-beta-binomial-distribution-1" id="toc-althams-multiplicative-beta-binomial-distribution-1" class="nav-link" data-scroll-target="#althams-multiplicative-beta-binomial-distribution-1"><span class="header-section-number">5.3</span> Altham’s Multiplicative Beta Binomial Distribution</a></li>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link" data-scroll-target="#executive-summary"><span class="header-section-number">5.4</span> Executive Summary</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab10WriteUp.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab Ten – Point Estimation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p></p>
<p></p>
<p><strong>Tips</strong></p>
<ul>
<li>Complete the tasks below. Make sure to start your solutions in on a new line that starts with “<strong>Solution</strong>:”.</li>
<li>Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab <em>much</em> easier.</li>
<li>Make sure to use “enter” to make your code readable, so it doesn’t run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you’re submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.</li>
<li>Don’t forget that you can copy-and-paste code when you’re doing something similar as we did in class!</li>
<li>Make sure to plot all computed probabilities. This is good <code>ggplot</code> practice AND will help make sure you don’t make a mistake when computing the probability.</li>
</ul>
<section id="lab-8-notes" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Lab 8 Notes</h1>
<section id="althams-multiplicative-binomial-distribution" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="althams-multiplicative-binomial-distribution"><span class="header-section-number">1.1</span> Altham’s Multiplicative Binomial Distribution</h2>
<p>The PMF for Altham’s Multiplicative Binomial Distribution is <span class="math display">\[f_X(x) = \frac{1}{c} {n \choose x} p^x (1-p)^{n-x} \theta^{x(n-x)}I(x \in \{0, 1, ..., n\})\]</span> where <span class="math display">\[c = \sum_{i=0}^n {n \choose i} p^i (1-p)^{n-i} \theta^{i(n-i)}.\]</span> Just so we start on the same page, I have included my <code>R</code> function for computing probability using this distribution.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>daltbinom <span class="ot">&lt;-</span> <span class="cf">function</span>(x, size, prob, theta){</span>
<span id="cb1-2"><a href="#cb1-2"></a>  normalizing.constant <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>  <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>size){</span>
<span id="cb1-4"><a href="#cb1-4"></a>    normalizing.constant <span class="ot">&lt;-</span> normalizing.constant <span class="sc">+</span> </span>
<span id="cb1-5"><a href="#cb1-5"></a>      <span class="fu">choose</span>(size, j) <span class="sc">*</span> prob<span class="sc">^</span>j <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>prob)<span class="sc">^</span>(size<span class="sc">-</span>j) <span class="sc">*</span> theta<span class="sc">^</span>(j<span class="sc">*</span>(size<span class="sc">-</span>j))</span>
<span id="cb1-6"><a href="#cb1-6"></a>  }</span>
<span id="cb1-7"><a href="#cb1-7"></a>  <span class="co"># Probability Mass at x=x</span></span>
<span id="cb1-8"><a href="#cb1-8"></a>  (<span class="dv">1</span><span class="sc">/</span>normalizing.constant) <span class="sc">*</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>    <span class="fu">choose</span>(size, x) <span class="sc">*</span> prob<span class="sc">^</span>x <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>prob)<span class="sc">^</span>(size<span class="sc">-</span>x) <span class="sc">*</span> theta<span class="sc">^</span>(x<span class="sc">*</span>(size<span class="sc">-</span>x)) <span class="sc">*</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>      (x<span class="sc">&gt;=</span><span class="dv">0</span>)<span class="sc">*</span>(x<span class="sc">&lt;=</span>size)</span>
<span id="cb1-11"><a href="#cb1-11"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
</section>
<section id="althams-multiplicative-beta-binomial-distribution" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Altham’s Multiplicative Beta Binomial Distribution</h1>
<p>The PMF for Altham’s Multiplicative Beta Binomial Distribution is <span class="math display">\[f_X(x) = \left[\int_{0}^1 \left(\frac{1}{c} {n \choose x} p^x (1-p)^{n-x} \theta^{x(n-x)}\right)\left(\frac{\Gamma(\alpha+\beta)}{\Gamma(\alpha)\Gamma(\beta)} p^{\alpha-1}(1-p)^{\beta-1}\right) dp\right]I(x \in \{0, 1, ..., n\})\]</span></p>
<p>Just so we start on the same page, I have included my <code>R</code> function for computing probability using this distribution.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>daltbbinom.single <span class="ot">&lt;-</span> <span class="cf">function</span>(x, size, alpha, beta, theta){</span>
<span id="cb2-2"><a href="#cb2-2"></a>    integrand <span class="ot">&lt;-</span> <span class="cf">function</span>(p) {</span>
<span id="cb2-3"><a href="#cb2-3"></a>    <span class="fu">sapply</span>(p, <span class="co"># integrate will pass in a vector, so we use sapply to apply the following</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>           <span class="cf">function</span>(p_val){</span>
<span id="cb2-5"><a href="#cb2-5"></a>             <span class="co"># f(x|p) * f(p|alpha, beta)</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>             <span class="fu">daltbinom</span>(x, size, p_val, theta) <span class="sc">*</span> <span class="fu">dbeta</span>(p_val, alpha, beta)</span>
<span id="cb2-7"><a href="#cb2-7"></a>           }</span>
<span id="cb2-8"><a href="#cb2-8"></a>    )</span>
<span id="cb2-9"><a href="#cb2-9"></a>  }</span>
<span id="cb2-10"><a href="#cb2-10"></a>  <span class="co"># Probability Mass at x=x</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>  <span class="co"># integrate(integrand, lower = 0, upper = 1)$value * (x&gt;=0)*(x&lt;=size)</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>  <span class="co"># I shrink the bounds below to avoid log(0)=-infinty</span></span>
<span id="cb2-13"><a href="#cb2-13"></a>  <span class="co"># I use try() to catch when there is an error and avoid crashing</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>  res <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">integrate</span>(integrand, <span class="at">lower =</span> <span class="fl">1e-7</span>, <span class="at">upper =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">1e-7</span>)<span class="sc">$</span>value <span class="sc">*</span> </span>
<span id="cb2-15"><a href="#cb2-15"></a>                  (x<span class="sc">&gt;=</span><span class="dv">0</span>)<span class="sc">*</span>(x<span class="sc">&lt;=</span>size), </span>
<span id="cb2-16"><a href="#cb2-16"></a>             <span class="at">silent =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-17"><a href="#cb2-17"></a>  <span class="co"># If there is an error, return a near-zero probability</span></span>
<span id="cb2-18"><a href="#cb2-18"></a>  <span class="cf">if</span>(<span class="fu">inherits</span>(res, <span class="st">"try-error"</span>)) <span class="fu">return</span>(<span class="fl">0.1</span><span class="sc">^</span><span class="dv">6</span>)</span>
<span id="cb2-19"><a href="#cb2-19"></a>  </span>
<span id="cb2-20"><a href="#cb2-20"></a>  res</span>
<span id="cb2-21"><a href="#cb2-21"></a>}</span>
<span id="cb2-22"><a href="#cb2-22"></a><span class="co"># Write a function that works on a vector</span></span>
<span id="cb2-23"><a href="#cb2-23"></a>daltbbinom <span class="ot">&lt;-</span> <span class="cf">function</span>(x, size, alpha, beta, theta){</span>
<span id="cb2-24"><a href="#cb2-24"></a>  <span class="fu">sapply</span>(<span class="at">X=</span>x, <span class="at">FUN=</span>daltbbinom.single, <span class="at">size=</span>size, <span class="at">alpha=</span>alpha, <span class="at">beta=</span>beta, <span class="at">theta=</span>theta)</span>
<span id="cb2-25"><a href="#cb2-25"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
<section id="question-1" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Question 1</h1>
<p>In Lab 8, we use Altham’s Multiplicative Binomial Distribution. Your job was to interpret the impact of <span class="math inline">\(\theta\)</span> in that equation. In this lab, we will model the number of legs won in a best of eleven (first to six) match.</p>
<p>To help us think about the interpretation, something that was challenging before, let’s try something a little more manageable.</p>
<section id="part-a" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="part-a"><span class="header-section-number">3.1</span> Part a</h2>
<p>Suppose a player has a 50% chance of winning a specific leg, that is let <span class="math inline">\(p=0.50\)</span>. Let’s look at the probability they win (<span class="math inline">\(x=6\)</span>) legs in the match. Compute this probability over a sequence from <span class="math inline">\(\theta=0.5\)</span> to <span class="math inline">\(\theta=1.5\)</span> and plot it using a line where the <span class="math inline">\(x\)</span>-axis is <span class="math inline">\(\theta\)</span> and the <span class="math inline">\(y\)</span>-axis is <span class="math inline">\(P(X=6)\)</span>.</p>
<p><strong>Solution</strong></p>
<p>I created a faux continuous sequence of theta values by creating a vector of very small values between 0 and 1.5 theta. I then applied althams binomial distribution to the ‘continuous’ theta values looking for where X is exactly 6, or win the game. We see its not very likely for a player to win exaclty 6 matches when theta is low, but that probility goes up at theta does.</p>
<p></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>prob_data <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb3-2"><a href="#cb3-2"></a>  <span class="at">theta =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">1.5</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb3-3"><a href="#cb3-3"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-5"><a href="#cb3-5"></a>    <span class="at">prob_6 =</span> <span class="fu">sapply</span>(theta, <span class="cf">function</span>(theta_sing){</span>
<span id="cb3-6"><a href="#cb3-6"></a>      <span class="fu">daltbinom</span>(<span class="at">x=</span><span class="dv">6</span>, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">theta =</span> theta_sing)</span>
<span id="cb3-7"><a href="#cb3-7"></a>    })</span>
<span id="cb3-8"><a href="#cb3-8"></a>  )</span>
<span id="cb3-9"><a href="#cb3-9"></a></span>
<span id="cb3-10"><a href="#cb3-10"></a>prob_data <span class="sc">|&gt;</span></span>
<span id="cb3-11"><a href="#cb3-11"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> theta, <span class="at">y =</span> prob_6)) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb3-13"><a href="#cb3-13"></a>  <span class="fu">xlab</span>(<span class="st">"theta"</span>) <span class="sc">+</span></span>
<span id="cb3-14"><a href="#cb3-14"></a>  <span class="fu">ylab</span>(<span class="st">"P(X=6)"</span>) <span class="sc">+</span> </span>
<span id="cb3-15"><a href="#cb3-15"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Probability of Winning 6 Legs</figcaption>
<p><img src="Lab10WriteUp_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p></p>
</section>
<section id="part-b" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="part-b"><span class="header-section-number">3.2</span> Part b</h2>
<p>Now, plot Altham’s Multiplicative Binomial Distribution under the same parameters with <span class="math inline">\(\theta=0.50\)</span>, <span class="math inline">\(\theta=1\)</span>, and <span class="math inline">\(\theta=1.5\)</span>. Use <code>ncol=1</code> in <code>facet_wrap()</code> to plot the PMFs in a single column for comparing.</p>
<p><strong>Solution</strong></p>
<p>Now I applied althams on specific theta values and on a range of x values, or number of wins, in order to show the probability of number of wins depending on theta values.</p>
<p></p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a>pmf_05 <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb4-2"><a href="#cb4-2"></a>  <span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">11</span>,</span>
<span id="cb4-3"><a href="#cb4-3"></a>  <span class="at">theta =</span> <span class="fl">0.5</span>,</span>
<span id="cb4-4"><a href="#cb4-4"></a>  <span class="at">prob =</span> <span class="fu">sapply</span>(x, <span class="cf">function</span>(x_val){</span>
<span id="cb4-5"><a href="#cb4-5"></a>    <span class="fu">daltbinom</span>(<span class="at">x =</span> x_val, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">theta =</span> <span class="fl">0.5</span>)</span>
<span id="cb4-6"><a href="#cb4-6"></a>  })</span>
<span id="cb4-7"><a href="#cb4-7"></a>)</span>
<span id="cb4-8"><a href="#cb4-8"></a></span>
<span id="cb4-9"><a href="#cb4-9"></a>pmf_1 <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb4-10"><a href="#cb4-10"></a>  <span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">11</span>,</span>
<span id="cb4-11"><a href="#cb4-11"></a>  <span class="at">theta =</span> <span class="dv">1</span>,</span>
<span id="cb4-12"><a href="#cb4-12"></a>  <span class="at">prob =</span> <span class="fu">sapply</span>(x, <span class="cf">function</span>(x_val){</span>
<span id="cb4-13"><a href="#cb4-13"></a>    <span class="fu">daltbinom</span>(<span class="at">x =</span> x_val, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">theta =</span> <span class="dv">1</span>)</span>
<span id="cb4-14"><a href="#cb4-14"></a>  })</span>
<span id="cb4-15"><a href="#cb4-15"></a>)</span>
<span id="cb4-16"><a href="#cb4-16"></a></span>
<span id="cb4-17"><a href="#cb4-17"></a>pmf_15 <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb4-18"><a href="#cb4-18"></a>  <span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">11</span>,</span>
<span id="cb4-19"><a href="#cb4-19"></a>  <span class="at">theta =</span> <span class="fl">1.5</span>,</span>
<span id="cb4-20"><a href="#cb4-20"></a>  <span class="at">prob =</span> <span class="fu">sapply</span>(x, <span class="cf">function</span>(x_val){</span>
<span id="cb4-21"><a href="#cb4-21"></a>    <span class="fu">daltbinom</span>(<span class="at">x =</span> x_val, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">prob =</span> <span class="fl">0.5</span>, <span class="at">theta =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-22"><a href="#cb4-22"></a>  })</span>
<span id="cb4-23"><a href="#cb4-23"></a>)</span>
<span id="cb4-24"><a href="#cb4-24"></a></span>
<span id="cb4-25"><a href="#cb4-25"></a>pmf_data <span class="ot">=</span> <span class="fu">bind_rows</span>(pmf_05, pmf_1, pmf_15)</span>
<span id="cb4-26"><a href="#cb4-26"></a></span>
<span id="cb4-27"><a href="#cb4-27"></a>pmf_data <span class="sc">|&gt;</span></span>
<span id="cb4-28"><a href="#cb4-28"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> prob)) <span class="sc">+</span></span>
<span id="cb4-29"><a href="#cb4-29"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-30"><a href="#cb4-30"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>theta, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-31"><a href="#cb4-31"></a>  <span class="fu">xlab</span>(<span class="st">"x"</span>) <span class="sc">+</span></span>
<span id="cb4-32"><a href="#cb4-32"></a>  <span class="fu">ylab</span>(<span class="st">"P(X=x)"</span>) <span class="sc">+</span></span>
<span id="cb4-33"><a href="#cb4-33"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Altham’s for theta = 0.5, 1, 1.5</figcaption>
<p><img src="Lab10WriteUp_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p></p>
</section>
<section id="part-c" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="part-c"><span class="header-section-number">3.3</span> Part c</h2>
<p>What is your best assessment of what <span class="math inline">\(\theta\)</span> is doing in this setting. Consider when a 6-0 blowout is most likely, and when a 5-6 nail-biter is most likely. Note here we should treat the match as a fixed <span class="math inline">\(n=11\)</span> as we did for <span class="math inline">\(n=3\)</span> in Lab 8.<br>
<strong>Note:</strong> In lab 8, we saw that small <span class="math inline">\(\theta\)</span> meant wins came in bunches (clumped together), so there were more 2-0 wins in a best of three series.</p>
<p><strong>Solution</strong></p>
<p>Here theta is clumping wins and losses. So when theta is small it clumps more, as seen in the theta = 0.5 graph. We see that the greatest probability is attributed to a blowout in either direction, either 11-0 or 0-11. Now when theta is 1, our althams reduces to just a beta distribution looking gaussian. So the probability is centered around 5 or 6 wins but slowly tails off on either side. Now when theta is high like at theta = 1.5, we see a much more tightly centered distribution. The wins are much more centered around 5 or 6 wins which gives a higher likelihood of a nail-biter game, with scores like 5-6 or 6-5.</p>
</section>
</section>
<section id="question-2" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Question 2</h1>
<section id="part-a-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="part-a-1"><span class="header-section-number">4.1</span> Part a</h2>
<p>Altham’s Multiplicative Binomial Distribution does not typically simplify to the clean <span class="math inline">\(E(X)=np\)</span> seen in the Binomial distribution, unless <span class="math inline">\(\theta = 1\)</span>. Write out the expression that would need to be solved to find <span class="math inline">\(E(X^k)\)</span>, and then write a function that computes it given the proposed parameter values <span class="math inline">\(p\)</span> (<code>prob</code>) and <span class="math inline">\(\theta\)</span> (<code>theta</code>).</p>
<p><strong>Solution</strong></p>
<p>To solve <span class="math inline">\(E(X^k)\)</span>, the expression follows:</p>
<p><span class="math display">\[E(X^k) = \sum_{x=0}^{n} x^k P(X=x). \]</span></p>
<p>Then, I just created a simple function that emulates this expression for varying prob and theta values, also size as well.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>altham_moment <span class="ot">=</span> <span class="cf">function</span>(size, k, prob, theta){</span>
<span id="cb5-2"><a href="#cb5-2"></a>  x_vals <span class="ot">=</span> <span class="dv">0</span><span class="sc">:</span>size</span>
<span id="cb5-3"><a href="#cb5-3"></a></span>
<span id="cb5-4"><a href="#cb5-4"></a>  moment <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(x_vals, <span class="cf">function</span>(x){ <span class="co">#sums all together</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>    (x<span class="sc">^</span>k)<span class="sc">*</span><span class="fu">daltbinom</span>(<span class="at">x =</span> x, <span class="at">size =</span> size, <span class="at">prob =</span> prob, <span class="at">theta =</span> theta)</span>
<span id="cb5-6"><a href="#cb5-6"></a>    })</span>
<span id="cb5-7"><a href="#cb5-7"></a>  )</span>
<span id="cb5-8"><a href="#cb5-8"></a>  <span class="fu">return</span>(moment)</span>
<span id="cb5-9"><a href="#cb5-9"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
<section id="part-b-1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="part-b-1"><span class="header-section-number">4.2</span> Part b</h2>
<p>Describe how you can use your answer to part a to find Method of Moments estimates for the parameters <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> for Altham’s Multiplicative Binomial Distribution based on data.</p>
<p><strong>Solution</strong></p>
<p>I will get sample moments from the data, then compute theoretical moments from the model, set them equal to each other and solve for <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>. Because there are two parameters, I am going to need at least two equations. I would use the first two moments as my equations. I would get my first two moments of the model using my function from the previous part. I would get my first two moments of the data by:</p>
<p><span class="math display">\[ E(X) = \frac{1}{n} \sum_{i=1}^{n} X_i \]</span></p>
<p>and:</p>
<p><span class="math display">\[ E(X^2) = \frac{1}{n} \sum_{i=1}^{n} X_i^2 \]</span></p>
<p>I would then set the moments from the model equal to the moments from the data and solve them simultaneously for <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>.</p>
</section>
<section id="part-c-1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="part-c-1"><span class="header-section-number">4.3</span> Part c</h2>
<p>Write a function that computes the log-likelihood for Altham’s Multiplicative Binomial Distribution, given data (<code>x</code>) and proposed parameter values <span class="math inline">\(p\)</span> (<code>prob</code>) and <span class="math inline">\(\theta\)</span> (<code>theta</code>).</p>
<p><strong>Solution</strong></p>
<p>I made my function, remembering to keep the log inside the summation. It really is just the sum of the log probabilities. I also made my function support a size parameter because I’m cool like that.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>altham_loglike <span class="ot">=</span> <span class="cf">function</span>(x, size, prob, theta){</span>
<span id="cb6-2"><a href="#cb6-2"></a>  loglike <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">log</span>(</span>
<span id="cb6-3"><a href="#cb6-3"></a>    <span class="fu">sapply</span>(x, <span class="cf">function</span>(x_val){</span>
<span id="cb6-4"><a href="#cb6-4"></a>      <span class="fu">daltbinom</span>(<span class="at">x=</span>x_val, <span class="at">size =</span> size, <span class="at">prob =</span> prob, <span class="at">theta =</span> theta)</span>
<span id="cb6-5"><a href="#cb6-5"></a>    })</span>
<span id="cb6-6"><a href="#cb6-6"></a>  ))</span>
<span id="cb6-7"><a href="#cb6-7"></a>  <span class="fu">return</span>(loglike)</span>
<span id="cb6-8"><a href="#cb6-8"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
<section id="part-d" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="part-d"><span class="header-section-number">4.4</span> Part d</h2>
<p>Describe how you can use your answer to part c to find Maximum Likelihood estimates for the parameters <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> for Altham’s Multiplicative Binomial Distribution based on data.</p>
<p><strong>Solution</strong></p>
<p>I would use the log-likelihood function and maximize it with respect to <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> on the data. I wouldn’t do this by hand, but numerically using optim. To keep real parameter values I would transform them such that <span class="math inline">\(0 &lt; p &lt; 1\)</span> and <span class="math inline">\(\theta &gt; 0\)</span>.</p>
</section>
</section>
<section id="lab-10" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Lab 10</h1>
<p>Peter “Snakebite” Wright is a two-time Professional Darts Corporation World Champion (2020, 2022) and a former World No.&nbsp;1. He is one of the sport’s most decorated players, winning nearly 50 PDC titles including the World Matchplay, UK Open, and multiple European Championships.</p>
<p>In 2024, he made The Premier League – a league involving the eight best players that runs every Thursday night from February to May. In this season, he won two of eighteen matches, securing only four points. The spread in legs won was -43, meaning he lost 43 more legs than he won. This performance was rather quite bad. He was soundly trounced in almost all his match ups.</p>
<p>The 2024 standings are below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Rank</th>
<th style="text-align: left;">Player</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Luke Littler</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Luke Humphries</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Michael van Gerwen</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Michael Smith</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Nathan Aspinall</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Rob Cross</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Gerwyn Price</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Peter Wright</td>
</tr>
</tbody>
</table>
<section id="summarize-the-2024-data" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="summarize-the-2024-data"><span class="header-section-number">5.1</span> Summarize the 2024 Data</h2>
<p>In <code>pdc2024.csv</code>, I have provided the data for the 2024 Premier League season. There are a few data cleaning steps to consider.</p>
<ul>
<li>Remove any matches with no <code>Score</code> (e.g., a bye or walkover)</li>
<li>Nights 1 through 16 are best of 11 (first to 6), but the playoffs are extended. For consistency, keep nights 1 through 16 only.</li>
<li>Make two columns <code>WinnerLegs</code> and <code>LoserLegs</code> that keep track of the number of legs each player has won</li>
</ul>
<p>Summarize the data. What do the data tell us about the breakdown of the results?</p>
<p><strong>Solution</strong></p>
<p>Our normal summary stats don’t tell us much here, other than the average number of legs the loser has in a game is around 4 (3.56) legs, before they lose. We also see that a total of 111 matches were played. From the player summary we get some more insight. Luke Littler has the most amount of wins, followed by Luke Humphries and Michael Smith. This is telling about the final standings of the tournament where Luke Littler won first place and Luke Humphries came second. However Michael Smith may have won more games than Michael van Gerwen, yet van Gerwen still placed higher. This tells us that it is not always the case that more games won means higher placement. My intuition tells me that it is more important to win the more crucial games than it is to have a higher winning rate. We also see a nice correlation of wins to matches played here.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>pdc2024 <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"pdc2024.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a>pdc_clean <span class="ot">=</span> pdc2024 <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">filter</span>(Score <span class="sc">!=</span> <span class="st">"w/o"</span>) <span class="sc">|&gt;</span> <span class="co">#takes out no score games</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>  <span class="fu">filter</span>(Night <span class="sc">!=</span> <span class="st">"Finals"</span>) <span class="sc">|&gt;</span> <span class="co">#takes out finals nights</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="fu">separate_wider_delim</span>(Score, <span class="at">delim =</span> <span class="st">"-"</span>, <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"WinnerLegs"</span>, <span class="st">"LoserLegs"</span>)) <span class="sc">|&gt;</span> <span class="co">#separates score into two new columns based on "-"</span></span>
<span id="cb7-7"><a href="#cb7-7"></a></span>
<span id="cb7-8"><a href="#cb7-8"></a>  <span class="fu">mutate</span>(<span class="at">WinnerLegs =</span> <span class="fu">as.numeric</span>(WinnerLegs), </span>
<span id="cb7-9"><a href="#cb7-9"></a>          <span class="at">LoserLegs =</span> <span class="fu">as.numeric</span>(LoserLegs)) <span class="co">#made them numeric here, seems like it will be useful later on</span></span>
<span id="cb7-10"><a href="#cb7-10"></a></span>
<span id="cb7-11"><a href="#cb7-11"></a><span class="co">#summary part</span></span>
<span id="cb7-12"><a href="#cb7-12"></a></span>
<span id="cb7-13"><a href="#cb7-13"></a>summary_stats <span class="ot">=</span> pdc_clean <span class="sc">|&gt;</span></span>
<span id="cb7-14"><a href="#cb7-14"></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-15"><a href="#cb7-15"></a>    <span class="at">TotalMatches =</span> <span class="fu">n</span>(),</span>
<span id="cb7-16"><a href="#cb7-16"></a>    <span class="at">AvgWinnerLegs =</span> <span class="fu">mean</span>(WinnerLegs), <span class="co">#obv always going to be 6, but i put it in anyways</span></span>
<span id="cb7-17"><a href="#cb7-17"></a>    <span class="at">AvgLoserLegs =</span> <span class="fu">mean</span>(LoserLegs),</span>
<span id="cb7-18"><a href="#cb7-18"></a>    <span class="at">MinLoserLegs =</span> <span class="fu">min</span>(LoserLegs),</span>
<span id="cb7-19"><a href="#cb7-19"></a>    <span class="at">MaxLoserLegs =</span> <span class="fu">max</span>(LoserLegs)</span>
<span id="cb7-20"><a href="#cb7-20"></a>  )</span>
<span id="cb7-21"><a href="#cb7-21"></a></span>
<span id="cb7-22"><a href="#cb7-22"></a>summary_stats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  TotalMatches AvgWinnerLegs AvgLoserLegs MinLoserLegs MaxLoserLegs
         &lt;int&gt;         &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt;
1          111             6         3.56            1            5</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>wins_summary <span class="ot">=</span> pdc_clean <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>  <span class="fu">group_by</span>(Winner) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">summarize</span>(<span class="at">Wins =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">mutate</span>(<span class="at">Player =</span> Winner)</span>
<span id="cb9-5"><a href="#cb9-5"></a></span>
<span id="cb9-6"><a href="#cb9-6"></a>losses_summary <span class="ot">=</span> pdc_clean <span class="sc">|&gt;</span></span>
<span id="cb9-7"><a href="#cb9-7"></a>  <span class="fu">group_by</span>(Loser) <span class="sc">|&gt;</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>  <span class="fu">summarize</span>(<span class="at">Losses =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb9-9"><a href="#cb9-9"></a>  <span class="fu">mutate</span>(<span class="at">Player =</span> Loser)</span>
<span id="cb9-10"><a href="#cb9-10"></a></span>
<span id="cb9-11"><a href="#cb9-11"></a>player_summary <span class="ot">=</span> <span class="fu">full_join</span>(wins_summary, losses_summary, <span class="at">by =</span> <span class="st">"Player"</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-12"><a href="#cb9-12"></a>  <span class="fu">mutate</span>(<span class="at">Matches =</span> Wins <span class="sc">+</span> Losses) <span class="sc">|&gt;</span></span>
<span id="cb9-13"><a href="#cb9-13"></a>  <span class="fu">select</span>(Player, Wins, Losses, Matches) <span class="sc">|&gt;</span> <span class="co">#my mediocre fix to keep wins losses and matches only</span></span>
<span id="cb9-14"><a href="#cb9-14"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Wins)) <span class="co">#arranged by wins</span></span>
<span id="cb9-15"><a href="#cb9-15"></a></span>
<span id="cb9-16"><a href="#cb9-16"></a>player_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  Player              Wins Losses Matches
  &lt;chr&gt;              &lt;int&gt;  &lt;int&gt;   &lt;int&gt;
1 Luke Littler          24     12      36
2 Luke Humphries        20     12      32
3 Michael Smith         17     14      31
4 Michael van Gerwen    16     12      28
5 Nathan Aspinall       15     14      29
6 Rob Cross             10     16      26
7 Gerwyn Price           7     15      22
8 Peter Wright           2     16      18</code></pre>
</div>
</div>
<p></p>
</section>
<section id="althams-multiplicative-binomial-distribution-1" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="althams-multiplicative-binomial-distribution-1"><span class="header-section-number">5.2</span> Altham’s Multiplicative Binomial Distribution</h2>
<p>For each player in the 2024 season, use the number of legs won in each match to compute maximium likelihood estimates for <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>.<br>
<strong>Note</strong>: The “for each” here can be done more efficiently with a function or a loop!</p>
<ul>
<li>Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner’s legs and sometimes from the loser’s legs.</li>
<li>Find the MLE for the player using this data. Ensure to report <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> for each player in a nicely formatted table.<br>
<strong>Note:</strong> In Lecture on Monday, we used transformations to restrict how <code>optim()</code> searches the parameter space. For example, here, you might consider <code>p &lt;- 1/(1+exp(-par[1]))</code> and <code>theta &lt;- exp(par[2])</code>.</li>
<li>Make comments about the MLEs in the context of the standings.</li>
</ul>
<p><strong>Solution</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>winner_legs <span class="ot">=</span> pdc_clean <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="fu">select</span>(<span class="at">Player =</span> Winner, <span class="at">LegsWon =</span> WinnerLegs)</span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a>loser_legs <span class="ot">=</span> pdc_clean <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5"></a>  <span class="fu">select</span>(<span class="at">Player =</span> Loser, <span class="at">LegsWon =</span> LoserLegs)</span>
<span id="cb11-6"><a href="#cb11-6"></a></span>
<span id="cb11-7"><a href="#cb11-7"></a>player_legs <span class="ot">=</span> <span class="fu">bind_rows</span>(winner_legs, loser_legs) <span class="co">#this has all the won legs from both when they win or lose the overall matches</span></span>
<span id="cb11-8"><a href="#cb11-8"></a></span>
<span id="cb11-9"><a href="#cb11-9"></a>ll_altham <span class="ot">=</span> <span class="cf">function</span>(par, data, size, <span class="at">mle =</span> F){ <span class="co">#this was all adapted from class notes</span></span>
<span id="cb11-10"><a href="#cb11-10"></a>  prob <span class="ot">=</span> <span class="fu">ifelse</span>(mle, <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>par[<span class="dv">1</span>])), par[<span class="dv">1</span>]) <span class="co">#restricting</span></span>
<span id="cb11-11"><a href="#cb11-11"></a>  theta <span class="ot">=</span> <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">2</span>]), par[<span class="dv">2</span>])</span>
<span id="cb11-12"><a href="#cb11-12"></a></span>
<span id="cb11-13"><a href="#cb11-13"></a>  ll <span class="ot">=</span> <span class="fu">altham_loglike</span>(<span class="at">x =</span> data, <span class="at">size =</span> size, <span class="at">prob =</span> prob, <span class="at">theta =</span> theta)</span>
<span id="cb11-14"><a href="#cb11-14"></a></span>
<span id="cb11-15"><a href="#cb11-15"></a>  <span class="fu">ifelse</span>(mle, <span class="sc">-</span>ll, ll)</span>
<span id="cb11-16"><a href="#cb11-16"></a>}</span>
<span id="cb11-17"><a href="#cb11-17"></a></span>
<span id="cb11-18"><a href="#cb11-18"></a>get_altham_mle <span class="ot">=</span> <span class="cf">function</span>(data, size){ <span class="co">#function to grab params by player</span></span>
<span id="cb11-19"><a href="#cb11-19"></a>  mle <span class="ot">=</span> <span class="fu">optim</span>(</span>
<span id="cb11-20"><a href="#cb11-20"></a>    <span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="co">#starting val</span></span>
<span id="cb11-21"><a href="#cb11-21"></a>    <span class="at">fn =</span> ll_altham, <span class="co">#my function for optim</span></span>
<span id="cb11-22"><a href="#cb11-22"></a>    <span class="at">data =</span> data,</span>
<span id="cb11-23"><a href="#cb11-23"></a>    <span class="at">size =</span> size,</span>
<span id="cb11-24"><a href="#cb11-24"></a>    <span class="at">mle =</span> T</span>
<span id="cb11-25"><a href="#cb11-25"></a>  )</span>
<span id="cb11-26"><a href="#cb11-26"></a></span>
<span id="cb11-27"><a href="#cb11-27"></a>  <span class="fu">return</span>(<span class="fu">c</span>(<span class="at">prob =</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>mle<span class="sc">$</span>par[<span class="dv">1</span>])), <span class="at">theta =</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">2</span>])) <span class="co">#results here</span></span>
<span id="cb11-28"><a href="#cb11-28"></a>  )</span>
<span id="cb11-29"><a href="#cb11-29"></a>}</span>
<span id="cb11-30"><a href="#cb11-30"></a></span>
<span id="cb11-31"><a href="#cb11-31"></a><span class="co">#formatting into nice table, filling values in from our mle function</span></span>
<span id="cb11-32"><a href="#cb11-32"></a><span class="co">#i struggled with this a lot, ive been having a tough time figuring out how to nicely set up tables... </span></span>
<span id="cb11-33"><a href="#cb11-33"></a><span class="co">#this was what i could come up with, but i hate it</span></span>
<span id="cb11-34"><a href="#cb11-34"></a></span>
<span id="cb11-35"><a href="#cb11-35"></a>players <span class="ot">=</span> <span class="fu">unique</span>(player_legs<span class="sc">$</span>Player) <span class="co">#only want one instance of each player</span></span>
<span id="cb11-36"><a href="#cb11-36"></a></span>
<span id="cb11-37"><a href="#cb11-37"></a>player_mle <span class="ot">=</span> <span class="fu">tibble</span>( <span class="co">#blank table first</span></span>
<span id="cb11-38"><a href="#cb11-38"></a>  <span class="at">Player =</span> <span class="fu">character</span>(),</span>
<span id="cb11-39"><a href="#cb11-39"></a>  <span class="at">prob =</span> <span class="fu">numeric</span>(),</span>
<span id="cb11-40"><a href="#cb11-40"></a>  <span class="at">theta =</span> <span class="fu">numeric</span>()</span>
<span id="cb11-41"><a href="#cb11-41"></a>)</span>
<span id="cb11-42"><a href="#cb11-42"></a></span>
<span id="cb11-43"><a href="#cb11-43"></a><span class="cf">for</span>(player_name <span class="cf">in</span> players){ </span>
<span id="cb11-44"><a href="#cb11-44"></a>  </span>
<span id="cb11-45"><a href="#cb11-45"></a>  player_data <span class="ot">=</span> player_legs <span class="sc">|&gt;</span> </span>
<span id="cb11-46"><a href="#cb11-46"></a>    <span class="fu">filter</span>(Player <span class="sc">==</span> player_name) <span class="co">#singling out</span></span>
<span id="cb11-47"><a href="#cb11-47"></a></span>
<span id="cb11-48"><a href="#cb11-48"></a>  player_data <span class="ot">=</span> player_data<span class="sc">$</span>LegsWon</span>
<span id="cb11-49"><a href="#cb11-49"></a>  </span>
<span id="cb11-50"><a href="#cb11-50"></a>  mle_fit <span class="ot">=</span> <span class="fu">get_altham_mle</span>(<span class="at">data =</span> player_data, <span class="at">size =</span> <span class="dv">11</span>) <span class="co">#applying function</span></span>
<span id="cb11-51"><a href="#cb11-51"></a>  </span>
<span id="cb11-52"><a href="#cb11-52"></a>  player_mle <span class="ot">=</span> <span class="fu">bind_rows</span>( <span class="co">#imputing values</span></span>
<span id="cb11-53"><a href="#cb11-53"></a>    player_mle, <span class="fu">tibble</span>(<span class="at">Player =</span> player_name,</span>
<span id="cb11-54"><a href="#cb11-54"></a>                      <span class="at">prob =</span> mle_fit[<span class="st">"prob"</span>],</span>
<span id="cb11-55"><a href="#cb11-55"></a>                      <span class="at">theta =</span> mle_fit[<span class="st">"theta"</span>])</span>
<span id="cb11-56"><a href="#cb11-56"></a>                ) <span class="sc">|&gt;</span></span>
<span id="cb11-57"><a href="#cb11-57"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(prob))</span>
<span id="cb11-58"><a href="#cb11-58"></a>}</span>
<span id="cb11-59"><a href="#cb11-59"></a></span>
<span id="cb11-60"><a href="#cb11-60"></a>player_mle</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  Player              prob theta
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;
1 Luke Littler       0.469 1.32 
2 Luke Humphries     0.461 1.20 
3 Michael van Gerwen 0.431 1.02 
4 Michael Smith      0.426 1.05 
5 Nathan Aspinall    0.403 1.19 
6 Rob Cross          0.395 1.01 
7 Gerwyn Price       0.383 1.02 
8 Peter Wright       0.317 0.989</code></pre>
</div>
</div>
<p></p>
<p>Given our MLE table, we see that Luke Littler has the highest prob and theta values. Our prob values are the probabilities of each player winning a leg, and thus, it follows that players who are better at winning a leg generally tend to do better in the competition. As we can see, Luke Littler has the highest prob value while placing first, and Peter Wright had the lowest prob value while placing last. The estimated theta values all are reasonably close to 1 here, which suggests that players’ matches don’t show that much bunching compared to the normal binomial case. However, Luke Littler’s theta is much higher (1.32), showcasing that his match results were much more competitive, rather than blow-outs. Overall, prob tends to better predict standings overall, while theta tends to better predict specific match result distributions.</p>
</section>
<section id="althams-multiplicative-beta-binomial-distribution-1" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="althams-multiplicative-beta-binomial-distribution-1"><span class="header-section-number">5.3</span> Altham’s Multiplicative Beta Binomial Distribution</h2>
<p>For each player in the 2024 season, use the number of legs won in each match to compute maxmium likelihood estimates for <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>.<br>
<strong>Note</strong>: The “for each” here can be done more efficiently with a function or a loop!</p>
<ul>
<li>Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner’s legs and sometimes from the loser’s legs.</li>
<li>Find the MLEs for the player using this data. Ensure to report <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, and <span class="math inline">\(\theta\)</span> for each player in a nicely formatted table.<br>
<strong>Note 1</strong>: Due to the computational complexity of <code>integrate()</code>, you should compute the logged probability for <code>0:6</code> once and add them according to the data in each player’s vector. <strong>Note 2</strong>: In Lecture on Monday, we used transformations to restrict how <code>optim()</code> searches the parameter space.</li>
<li>Plot the underlying Beta(<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>) distribution for each player.<br>
<strong>Note</strong>: Add the mean and variance of the Beta to the table of MLEs. Recall <span class="math display">\[\begin{align*}
E(X)   &amp;= \frac{\alpha}{\alpha+\beta}\\
sd(X) &amp;= \sqrt{\frac{\alpha\beta}{(\alpha+\beta)^2(\alpha+\beta+1)}}
\end{align*}\]</span></li>
<li>Make comments about the MLEs in the context of the standings.<br>
<strong>Note</strong>: The players alternate who throws first in a leg has the mathematical “head start” to reach a finish before their opponent can take another turn. Players alternate who throws first with each leg.</li>
</ul>
<p><strong>Solution</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>ll_altham_beta <span class="ot">=</span> <span class="cf">function</span>(par, data, size, <span class="at">mle =</span> F){ <span class="co">#same step where i adapted from class notes</span></span>
<span id="cb13-2"><a href="#cb13-2"></a>  alpha <span class="ot">=</span> <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">1</span>]), par[<span class="dv">1</span>]) <span class="co">#restricted by making them all positive via exponents</span></span>
<span id="cb13-3"><a href="#cb13-3"></a>  beta <span class="ot">=</span> <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">2</span>]), par[<span class="dv">2</span>])</span>
<span id="cb13-4"><a href="#cb13-4"></a>  theta <span class="ot">=</span> <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">3</span>]), par[<span class="dv">3</span>])</span>
<span id="cb13-5"><a href="#cb13-5"></a></span>
<span id="cb13-6"><a href="#cb13-6"></a>  probs <span class="ot">=</span> <span class="fu">daltbbinom</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> size, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta, <span class="at">theta =</span> theta) <span class="co">#precomputed probs as given in the note </span></span>
<span id="cb13-7"><a href="#cb13-7"></a></span>
<span id="cb13-8"><a href="#cb13-8"></a>  log_probs <span class="ot">=</span> <span class="fu">log</span>(probs) <span class="co">#now logged</span></span>
<span id="cb13-9"><a href="#cb13-9"></a></span>
<span id="cb13-10"><a href="#cb13-10"></a>  ll <span class="ot">=</span> <span class="fu">sum</span>(log_probs[data <span class="sc">+</span> <span class="dv">1</span>]) <span class="co">#need data+1 </span></span>
<span id="cb13-11"><a href="#cb13-11"></a>  <span class="co">#for indexing (stupid R indexes at 1 first, although this is nicer to read, i forgot abt this)</span></span>
<span id="cb13-12"><a href="#cb13-12"></a></span>
<span id="cb13-13"><a href="#cb13-13"></a>  <span class="fu">ifelse</span>(mle, <span class="sc">-</span>ll, ll)</span>
<span id="cb13-14"><a href="#cb13-14"></a>}</span>
<span id="cb13-15"><a href="#cb13-15"></a></span>
<span id="cb13-16"><a href="#cb13-16"></a>get_altham_beta_mle <span class="ot">=</span> <span class="cf">function</span>(data, size){ <span class="co">#same idea as before</span></span>
<span id="cb13-17"><a href="#cb13-17"></a>  mle <span class="ot">=</span> <span class="fu">optim</span>(</span>
<span id="cb13-18"><a href="#cb13-18"></a>    <span class="at">par =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="co">#start vals</span></span>
<span id="cb13-19"><a href="#cb13-19"></a>    <span class="at">fn =</span> ll_altham_beta,</span>
<span id="cb13-20"><a href="#cb13-20"></a>    <span class="at">data =</span> data,</span>
<span id="cb13-21"><a href="#cb13-21"></a>    <span class="at">size =</span> size,</span>
<span id="cb13-22"><a href="#cb13-22"></a>    <span class="at">mle =</span> T</span>
<span id="cb13-23"><a href="#cb13-23"></a>  )</span>
<span id="cb13-24"><a href="#cb13-24"></a>  <span class="fu">c</span>(<span class="at">alpha =</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">1</span>]),</span>
<span id="cb13-25"><a href="#cb13-25"></a>    <span class="at">beta =</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">2</span>]),</span>
<span id="cb13-26"><a href="#cb13-26"></a>    <span class="at">theta =</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">3</span>])</span>
<span id="cb13-27"><a href="#cb13-27"></a>  )</span>
<span id="cb13-28"><a href="#cb13-28"></a>}</span>
<span id="cb13-29"><a href="#cb13-29"></a></span>
<span id="cb13-30"><a href="#cb13-30"></a><span class="co">#exact same idea as before, just copy pasted and made changes</span></span>
<span id="cb13-31"><a href="#cb13-31"></a>players <span class="ot">=</span> <span class="fu">unique</span>(player_legs<span class="sc">$</span>Player)</span>
<span id="cb13-32"><a href="#cb13-32"></a></span>
<span id="cb13-33"><a href="#cb13-33"></a>player_beta_mle <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb13-34"><a href="#cb13-34"></a>  <span class="at">Player =</span> <span class="fu">character</span>(),</span>
<span id="cb13-35"><a href="#cb13-35"></a>  <span class="at">alpha =</span> <span class="fu">numeric</span>(),</span>
<span id="cb13-36"><a href="#cb13-36"></a>  <span class="at">beta =</span> <span class="fu">numeric</span>(),</span>
<span id="cb13-37"><a href="#cb13-37"></a>  <span class="at">theta =</span> <span class="fu">numeric</span>()</span>
<span id="cb13-38"><a href="#cb13-38"></a>)</span>
<span id="cb13-39"><a href="#cb13-39"></a></span>
<span id="cb13-40"><a href="#cb13-40"></a><span class="cf">for</span>(player_name <span class="cf">in</span> players){</span>
<span id="cb13-41"><a href="#cb13-41"></a>  </span>
<span id="cb13-42"><a href="#cb13-42"></a>  player_data <span class="ot">=</span> player_legs <span class="sc">|&gt;</span></span>
<span id="cb13-43"><a href="#cb13-43"></a>    <span class="fu">filter</span>(Player <span class="sc">==</span> player_name)</span>
<span id="cb13-44"><a href="#cb13-44"></a></span>
<span id="cb13-45"><a href="#cb13-45"></a>  player_data <span class="ot">=</span> player_data<span class="sc">$</span>LegsWon</span>
<span id="cb13-46"><a href="#cb13-46"></a>  </span>
<span id="cb13-47"><a href="#cb13-47"></a>  mle_fit <span class="ot">=</span> <span class="fu">get_altham_beta_mle</span>(<span class="at">data =</span> player_data, <span class="at">size =</span> <span class="dv">11</span>)</span>
<span id="cb13-48"><a href="#cb13-48"></a>  </span>
<span id="cb13-49"><a href="#cb13-49"></a>  player_beta_mle <span class="ot">=</span> <span class="fu">bind_rows</span>(</span>
<span id="cb13-50"><a href="#cb13-50"></a>    player_beta_mle,</span>
<span id="cb13-51"><a href="#cb13-51"></a>    <span class="fu">tibble</span>(<span class="at">Player =</span> player_name,</span>
<span id="cb13-52"><a href="#cb13-52"></a>      <span class="at">alpha =</span> mle_fit[<span class="st">"alpha"</span>],</span>
<span id="cb13-53"><a href="#cb13-53"></a>      <span class="at">beta =</span> mle_fit[<span class="st">"beta"</span>],</span>
<span id="cb13-54"><a href="#cb13-54"></a>      <span class="at">theta =</span> mle_fit[<span class="st">"theta"</span>]</span>
<span id="cb13-55"><a href="#cb13-55"></a>    )</span>
<span id="cb13-56"><a href="#cb13-56"></a>  )</span>
<span id="cb13-57"><a href="#cb13-57"></a>}</span>
<span id="cb13-58"><a href="#cb13-58"></a></span>
<span id="cb13-59"><a href="#cb13-59"></a>player_beta_mle <span class="ot">=</span> player_beta_mle <span class="sc">|&gt;</span> <span class="co">#adding var and E(X)</span></span>
<span id="cb13-60"><a href="#cb13-60"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-61"><a href="#cb13-61"></a>    <span class="at">mean =</span> alpha<span class="sc">/</span>(alpha<span class="sc">+</span>beta),</span>
<span id="cb13-62"><a href="#cb13-62"></a>    <span class="at">sd =</span> <span class="fu">sqrt</span>((alpha<span class="sc">*</span>beta) <span class="sc">/</span>(((alpha<span class="sc">+</span>beta)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(alpha<span class="sc">+</span>beta<span class="sc">+</span><span class="dv">1</span>)))</span>
<span id="cb13-63"><a href="#cb13-63"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb13-64"><a href="#cb13-64"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span>
<span id="cb13-65"><a href="#cb13-65"></a></span>
<span id="cb13-66"><a href="#cb13-66"></a><span class="co">#plotting section, i know this isnt optimal ("I CAN DO WHATEVER I WANT" - the great WC)</span></span>
<span id="cb13-67"><a href="#cb13-67"></a>p_vals <span class="ot">=</span> <span class="fu">seq</span>(<span class="fl">0.001</span>, <span class="fl">0.999</span>, <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb13-68"><a href="#cb13-68"></a></span>
<span id="cb13-69"><a href="#cb13-69"></a>beta_plot <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb13-70"><a href="#cb13-70"></a>  <span class="at">Player =</span> <span class="fu">rep</span>(player_beta_mle<span class="sc">$</span>Player, <span class="at">each =</span> <span class="fu">length</span>(p_vals)),</span>
<span id="cb13-71"><a href="#cb13-71"></a>  <span class="at">p =</span> <span class="fu">rep</span>(p_vals, <span class="at">times =</span> <span class="fu">nrow</span>(player_beta_mle)),</span>
<span id="cb13-72"><a href="#cb13-72"></a>  <span class="at">density =</span> <span class="fu">c</span>(</span>
<span id="cb13-73"><a href="#cb13-73"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">1</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">1</span>]),</span>
<span id="cb13-74"><a href="#cb13-74"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">2</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">2</span>]),</span>
<span id="cb13-75"><a href="#cb13-75"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">3</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">3</span>]),</span>
<span id="cb13-76"><a href="#cb13-76"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">4</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">4</span>]),</span>
<span id="cb13-77"><a href="#cb13-77"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">5</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">5</span>]),</span>
<span id="cb13-78"><a href="#cb13-78"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">6</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">6</span>]),</span>
<span id="cb13-79"><a href="#cb13-79"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">7</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">7</span>]),</span>
<span id="cb13-80"><a href="#cb13-80"></a>    <span class="fu">dbeta</span>(p_vals, <span class="at">shape1 =</span> player_beta_mle<span class="sc">$</span>alpha[<span class="dv">8</span>], <span class="at">shape2 =</span> player_beta_mle<span class="sc">$</span>beta[<span class="dv">8</span>])</span>
<span id="cb13-81"><a href="#cb13-81"></a>  )</span>
<span id="cb13-82"><a href="#cb13-82"></a>)</span>
<span id="cb13-83"><a href="#cb13-83"></a></span>
<span id="cb13-84"><a href="#cb13-84"></a>beta_plot <span class="sc">|&gt;</span></span>
<span id="cb13-85"><a href="#cb13-85"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p, <span class="at">y =</span> density)) <span class="sc">+</span></span>
<span id="cb13-86"><a href="#cb13-86"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-87"><a href="#cb13-87"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Player, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-88"><a href="#cb13-88"></a>  <span class="fu">xlab</span>(<span class="st">"p"</span>) <span class="sc">+</span></span>
<span id="cb13-89"><a href="#cb13-89"></a>  <span class="fu">ylab</span>(<span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb13-90"><a href="#cb13-90"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab10WriteUp_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co">#MLE table here (want to show last)</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>player_beta_mle</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 6
  Player             alpha  beta theta  mean    sd
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Luke Littler       0.283 0.384 10.8  0.425 0.383
2 Luke Humphries     0.331 0.490  6.39 0.403 0.363
3 Nathan Aspinall    2.47  4.34   1.49 0.363 0.172
4 Michael Smith      0.534 1.07   2.24 0.334 0.292
5 Michael van Gerwen 0.219 0.454  5.00 0.325 0.362
6 Rob Cross          0.268 0.813  3.20 0.248 0.299
7 Gerwyn Price       0.264 0.917  3.18 0.224 0.282
8 Peter Wright       1.79  7.29   1.21 0.197 0.125</code></pre>
</div>
</div>
<p></p>
<p>The MLEs mostly agree with the standings overall. Luke Littler has the greatest beta mean suggesting a greater leg-winning probability, while Peter Wright has the lowest beta mean matching his last place performance. Players between them seem to also have matching mean values relative to their standing. Theta values here were also very varying. Luke Littler had a massive theta value of 10.8, suggesting that his results were extremely centered around nail-biting matches, while Peter Wright had a much lower theta value, suggesting a less centered results distribution comparatively to Littler’s. Overall, the fitted beta means seem to capture standings pretty well, while theta helps to show match results distributions nicely.</p>
</section>
<section id="executive-summary" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="executive-summary"><span class="header-section-number">5.4</span> Executive Summary</h2>
<p>Summarize the work you’ve done here to provide a brief (200-300 word) data-driven summary of the 2024 Premier League season using your work in Lab 10. Your summary should be professional, clear, and all claims should be corroborated with statistical support.</p>
<p><strong>Solution</strong></p>
<p>While the competition was fierce, the results of a data-driven analysis showed clear differences in player strength. After removing the walkover and Finals rounds, the data set contained 111 matches played. The average number of legs won by the loser in a given match was 3.56, suggesting that most matches were close rather than complete blowouts. In the first player summary, Luke Littler had 24 wins, followed by Luke Humphries with 20, and in last place, Peter Wright only had 2 wins in the whole competition.</p>
<p>Using Altham’s Multiplicative Binomial Model, the estimated leg-win probability p did well to predict standings overall. Luke Littler had the largest p at 0.469, while Peter Wright had the lowest estimate p value at 0.317. The fitted theta values were close to 1, suggesting that most player’s matches were not much more clumped than the normal binomial model.</p>
<p>The Altham’s Multiplicative Beta-Binomial Model gave a more robust analysis by allowing the leg-win probability to vary a little bit across matches. The fitted beta means did well to predict standings overall here. Luke Littler had the highest with 0.425, followed by Luke Humphries, and again Peter Wright had the lowest at 0.197. The estimated theta values varied a lot here. Luke Littler had a theta value of 10.8, suggesting close and competitive match outcomes, while Peter Wright had a lower theta value of 1.21, suggesting less tightly centered match outcomes. Overall, this model gave a much more thorough analysis of the players’ qualities and matches’ variability.</p>
<p></p>
<p></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>